// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuffData } from "./BuffData";

export type AbilityScriptList = { scriptName: string, buffData: BuffData | null, };
