// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuffData = { buffKeyword: string | null, target: string | null, buffOwner: string | null, stack: bigint | null, turn: bigint | null, activeRound: bigint | null, };
