// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbilityScriptList } from "./AbilityScriptList";
import type { CoinTypes } from "./CoinTypes";

export type CoinList = { operatorType: CoinTypes, scale: bigint, abilityScriptList: Array<AbilityScriptList> | null, };
