// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillData } from "./SkillData";

export type Skill = {
	id: number;
	skillType: string | null;
	skillTier: bigint | null;
	requireIDList: Array<string | null> | null;
	skillData: Array<SkillData>;
};
